sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - docker --version
  - pip install awscli
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t cicdbuzz .
  - docker tag cicdbuzz:latest 757357302799.dkr.ecr.eu-west-1.amazonaws.com/thomas-cicd:latest
  - docker push 757357302799.dkr.ecr.eu-west-1.amazonaws.com/thomas-cicd:latest
